api:
  autodiscoveryId: "18690618"  

http:
 listener:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
 request:
  host: "sb-weborder-papi.us-e1.cloudhub.io"
  timeout: "30000"
  path: "/api/web_order"
  port: ""
  

